### CONTAINERS ###

init:
  clone:
    release: false
    #hostPath:

  manually:
    enabled: false
    repository: lead4good/init-wp
    tag: latest
    pullPolicy: Always

  resources: false

php:
  version: "7"
  #repository: php
  #tag: fpm
  pullPolicy: Always
  fpmEnabled: true
  sockets: true
  persistentSubpaths: false
  #- subPath
  copyRoot: false

  #oldHTTPRoot: /var/www/html
  #ini: |
  #  short_open_tag=On

  resources: false
  #  requests:
  #    cpu: 1m
  #    memory: 1Mi

httpd:
  resources: false
  #  requests:
  #    cpu: 1m
  #    memory: 1Mi


mysql:
  #rootPassword
  #user:
  #password:
  #database:

  repository: mysql
  tag: 5.7
  imagePullPolicy: Always
  sockets: true

  resources: false
  #  requests:
  #    cpu: 1m
  #    memory: 1Mi

sftp:
  enabled: false
  port: 22
  #nodePort:

  #user:
  #password:

  resources: false
  #  requests:
  #    cpu: 1m
  #    memory: 1Mi

webdav:
  enabled: false
  port: 8001
  subdomain: webdav

  #user:
  #password:

  resources: false
  #  requests:
  #    cpu: 1m
  #    memory: 1Mi

git:
  enabled: false
  branch: master
  revision: FETCH_HEAD
  wait: 30

  #repoURL:

  resources: false
  #  requests:
  #    cpu: 1m
  #    memory: 1Mi

svn:
  enabled: false
  allowOverwrite: true

  #user:
  #password:
  #repoURL:

  resources: false
  #  requests:
  #    cpu: 1m
  #    memory: 1Mi

phpmyadmin:
  enabled: false
  port: 8080
  subdomain: phpmyadmin

  resources: false
  #  requests:
  #    cpu: 1m
  #    memory: 1Mi

resources:
  requests:
    cpu: 1m
    memory: 1Mi


### STORAGE ###

persistence:
  enabled: true
  keep: false

  accessMode: ReadWriteOnce
  size: 5Gi

  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"

  #hostPath:


### NETWORKING ###

service:
  HTTPPort: 80
  type: LoadBalancer

ingress:
  enabled: false
  #domain: example.com
  #ssl: false
  #subdomainWWW: false
  #htpasswdString: "user:$apr1$FfVI2PRr$f9MW8rsr5RmmxbdV0Iipk1"

  annotations:
    ingress.kubernetes.io/proxy-body-size: "50m"
    kubernetes.io/ingress.class: nginx


### WORDPRESS ###

wordpress:
  enabled: false

  #gdriveRToken:
  #gdriveFolder: example.com
  #domain: "example.com"

  develop:
    enabled: false
    deleteUploads: false
    #devDomain: dev.example.com

### OTHER ###

keepSecrets: false
replicaCount: 1
