{{- if .Values.php.fpmEnabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{template "lamp.fullname" .}}-httpd
  labels:
    app: {{template "lamp.fullname" .}}
data:
{{ (.Files.Glob "files/httpd/httpd.conf").AsConfig | indent 2 }}
{{ (.Files.Glob "files/httpd/httpd-vhosts.conf").AsConfig | indent 2 }}
{{ (.Files.Glob "files/httpd/httpd-vhosts-socket.conf").AsConfig | indent 2 }}
{{- end }}
