{{- if or .Values.init.clone.release .Values.wordpress.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{template "fullname" .}}-init
  labels:
    app: {{template "fullname" .}}
data:
  {{- if .Values.init.clone.release }}
{{ (.Files.Glob "files/init/init_clone.sh").AsConfig | indent 2 }}
{{ (.Files.Glob "files/init/init_db_clone.sh").AsConfig | indent 2 }}
  {{- end }}
  {{- if .Values.wordpress.enabled }}
{{ (.Files.Glob "files/init/init_wp.sh").AsConfig | indent 2 }}
{{ (.Files.Glob "files/init/init_wp_db.sh").AsConfig | indent 2 }}
  {{- end }}

{{- if or .Values.mysql.sockets ( or .Values.php.fpm_enabled .Values.php.ini ) }}

---

{{- end }}
{{- end }}
{{- if or .Values.mysql.sockets ( or .Values.php.fpm_enabled .Values.php.ini ) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{template "fullname" .}}-php
  labels:
    app: {{template "fullname" .}}
data:
  additional.ini: |
  {{- if .Values.php.ini }}
{{ .Values.php.ini  | indent 4 }}
  {{- end }}
  {{- if .Values.mysql.sockets }}
    mysqli.default_socket=/var/run/mysqld/mysqld.sock
    pdo_mysql.default_socket=/var/run/mysqld/mysqld.sock
  {{- end }}
  {{- if .Values.php.fpm_enabled }}
  zz-docker.conf: |
    [global]
    daemonize = no
    [www]
    listen = /var/run/php/php-fpm.sock
    listen.mode = 0666
  {{- end }}
{{- end }}
